#!/usr/bin/env bash
# Build PureClick.app — a bundle you can keep in the Dock.
#
# The app is a Python program, so the bundle is a thin wrapper: its executable
# `exec`s the venv interpreter, which means the Python process *is* the bundle's
# main process. That matters — a launcher that merely spawns a child would leave
# the Dock showing a generic rocket and the windows unable to take focus.
#
# The repo path is baked in at build time. Move the repo and the app will say so
# rather than failing silently.
set -euo pipefail

MAC_DIR="$(cd "$(dirname "$0")" && pwd)"
DEST="${1:-$HOME/Applications}"
APP="$DEST/PureClick.app"

if [[ ! -x "$MAC_DIR/.venv/bin/python" ]]; then
  echo "No venv yet — run ./run_pureclick.sh once first, it builds one." >&2
  exit 1
fi

echo "drawing the icon…"
"$MAC_DIR/.venv/bin/python" "$MAC_DIR/make_icon.py"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$MAC_DIR/PureClick.icns" "$APP/Contents/Resources/PureClick.icns"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>              <string>PureClick</string>
  <key>CFBundleDisplayName</key>       <string>PureClick</string>
  <key>CFBundleExecutable</key>        <string>PureClick</string>
  <key>CFBundleIdentifier</key>        <string>com.minjaekim.pureclick</string>
  <key>CFBundleIconFile</key>          <string>PureClick</string>
  <key>CFBundlePackageType</key>       <string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key>           <string>1</string>
  <key>LSMinimumSystemVersion</key>    <string>11.0</string>
  <key>NSHighResolutionCapable</key>   <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/PureClick" <<LAUNCH
#!/bin/bash
# Generated by make_app.sh — edit that, not this.
MAC_DIR="$MAC_DIR"
LOG="\$HOME/Library/Logs/PureClick.log"
mkdir -p "\$(dirname "\$LOG")"

die() {
  # There is no terminal behind a Dock click, so a failure has to knock.
  osascript -e "display alert \"PureClick\" message \"\$1\" as critical" >/dev/null 2>&1
  exit 1
}

[[ -d "\$MAC_DIR" ]] || die "The app folder has moved. Rebuild with make_app.sh from wherever the repo lives now."
[[ -x "\$MAC_DIR/.venv/bin/python" ]] || die "No Python environment found. Open Terminal, run: cd \$MAC_DIR && ./run_pureclick.sh"

cd "\$MAC_DIR" || die "Could not open \$MAC_DIR"
echo "=== launched \$(date) ===" >> "\$LOG"
exec "\$MAC_DIR/.venv/bin/python" "\$MAC_DIR/pureclick.py" >> "\$LOG" 2>&1
LAUNCH

chmod +x "$APP/Contents/MacOS/PureClick"
# The icon cache keys off the bundle's mtime; without this the Dock can keep
# showing the generic executable icon for a bundle it has seen before.
touch "$APP"

echo
echo "built $APP"
echo "log:   ~/Library/Logs/PureClick.log"
